### ISSUE TITLE
Utilize dominators for constructing extended basic blocks

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#142]
Quoted from [Basic Blocks and CFG](http://www.cse.iitm.ac.in/~krishna/courses/2012/odd-cs3300/pm-lecture1.pdf), the definition of extended basic block (EBB):
* Extended basic block a maximal sequence of instructions beginning with a leader that contains no join nodes other than its first node.
* Has a single entry, but possible multiple exit points.
* Some optimizations are more effective on extended basic blocks.

<img width="283" src="https://github.com/sysprog21/rv32emu/assets/478921/ba5cbdbc-a101-43f0-981e-10812b8211f1">

We can identify loops by using [dominators](https://en.wikipedia.org/wiki/Dominator_(graph_theory)):
* a node A in the flowgraph dominates a node B if every path from entry node to B includes A.
* This relations is antisymmetric, reflexive, and transitive.

<img width="325" src="https://github.com/sysprog21/rv32emu/assets/478921/90510206-819a-4529-b389-982a4eadf985">

back edge: An edge in the flow graph, whose head dominates its tail (example - edge from B6 to B4).

A loop consists of all nodes dominated by its entry node (head of the back edge) and having exactly one back edge in it.

[Intercept](https://github.com/LensPlaysGames/Intercept) contains an effective [dominator](https://en.wikipedia.org/wiki/Dominator_(graph_theory)) implementation. See
* [src/ir/dom.c](https://github.com/LensPlaysGames/Intercept/blob/main/src/ir/dom.c)
* [src/codegen/opt/opt.c](https://github.com/LensPlaysGames/Intercept/blob/main/src/codegen/opt/opt.c)

Usage:
```c
void codegen_optimise(CodegenContext *ctx) {
  opt_inline_global_vars(ctx);
  opt_analyse_functions(ctx);

  /// Optimise each function individually.
  do {
    foreach_ptr (IRFunction*, f, ctx->functions) {
      if (f->is_extern) continue;

      DominatorInfo dom = {0};
      do {
        build_dominator_tree(f, &dom, true);
        opt_reorder_blocks(f, &dom);
      } while (
          opt_const_folding_and_strengh_reduction(f) ||
          opt_dce(f) ||
          opt_mem2reg(f) ||
          opt_jump_threading(f, &dom) ||
          opt_tail_call_elim(f)
      );
      free_dominator_info(&dom);
    }
  }

  /// Cross-function optimisations.
  while (opt_inline_global_vars(ctx) || opt_analyse_functions(ctx));
}
```

Similarly, [blink](https://github.com/jart/blink) comes with an approach to detect loops during code generation.

**Comment by jserv** [comment]
@qwe661234, per our discussion on Aug 29th, please present your conclusions derived from experimental exploration.

**Comment by qwe661234** [comment]
Previously, we employed recursive jump translation to implement an extended basic block. Nevertheless, this approach makes it challenging to detect loop paths since we position the loop's entry block inside the block, and its using frequency would not be updated.

Based on this observation, it becomes necessary to eliminate the recursive jump translation. By doing so, we can accurately update the using frequency of the loop's entry block.

![image](https://github.com/sysprog21/rv32emu/assets/48278026/77082afe-294b-43e6-b40f-ade7bb09fac8)

As shown in the performance results below, we gain 4% performance improvement when running coreMark and SciMark2 and lost 1% performance when running dhrysone.

* Intel Core i7-11700

| Metric | origin | proposed |Speedup|
|------------|---------|----------|-------|
| CoreMark | 2193.28 | 2289.26 | +4% |
| SciMark2 | 13.45 | 18.48 | +4% |
| Dhrystone | 1413.11 | 1447.11 | -1% |

**Comment by jserv** [comment]
The effectiveness has been confirmed. We shall look for further faster approaches for loop detection.
