### ISSUE TITLE
Handle argc/argv/envp properly

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#150]
On Linux, after argc, argv, and envp, there is auxv, which serves as a key-value store for binary data. However, current rv32emu fails to set argc, argc, and envp properly. They should be specified during the setting of default stack pointer.
```c
void rv_reset(riscv_t *rv, riscv_word_t pc)
{
    ...
    rv->X[rv_reg_sp] = DEFAULT_STACK_ADDR;
    ...
}
```

Reference:
* [pk.c](https://github.com/riscv-software-src/riscv-pk/blob/master/pk/pk.c): Check the comment "place argc, argv, envp, auxp on stack"
* [Where do argc and argv come from?](https://briancallahan.net/blog/20200808.html)

**Comment by jserv** [comment]
Once this task is complete, [readelf.c](https://github.com/sysprog21/rv32emu/blob/master/tests/readelf/readelf.c) can avoid hardcoded ELF path by obtaining argv instead.

**Comment by ChinYikMing** [comment]
I am working on solving this issue.

Currently, I am able to read `argc` but not `argv` and `envp`. The reason is due to 64-bit address space of emulator ( running on 64-bit machine ), so the `argv` and `envp ` address which stored on stack will be 64-bit, it makes the emulated program cannot get the `argv` and `envp` address by single 'lw' instruction( needs twice ).

Any ideas for translating 64-bit address to 32-bit address?

**Comment by jserv** [comment]
> Any ideas for translating 64-bit address to 32-bit address?

You may check the trick used in Erlang/OTP: https://www.erlang.org/blog/interpreter-optimizations/

**Comment by jserv** [comment]
[rvdbt](https://github.com/pooh64/rvdbt) manipulates initial vector. See https://github.com/pooh64/rvdbt/blob/main/dbt/ukernel.cpp (`ukernel::InitAVectors`)
