### ISSUE TITLE
jit: Fail to successfully execute the JIT assembler

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#168]
[xkon](https://github.com/ezaki-k/xkon_beta) was tested with interpreter. However, JIT compiler fails to execute it successfully.
The way to reproduce:
```
$ build/rvemu build/jit-bf.elf
```

Its output:
```
Execute 5 times with JIT precompile using xkon.

+0x2a = <.L0B>
+0x6e = <.L0E>
+0x118 = <.L1B>
+0x15c = <.L1E>
Address OPcode  ------- Instruction --------------------------------------------
...
??;(f0?Iaddi sp,sp,-32	# c.addi sp,-32
Segmentation fault (core dumped)

```

**Comment by jserv** [comment]
QEMU (w/ TCG) fails to run `jit-bf.elf` either.
```
$ qemu-riscv32 jit-bf.elf
...
Execute 5 times with JIT precompile using xkon.
+0x2c = <.L0B>
+0x70 = <.L0E>
+0x11a = <.L1B>
+0x15e = <.L1E>
Segmentation fault (core dumped)
```

**Comment by qwe661234** [comment]
After applying the PR #175 patch, this testcase sometimes passes and sometimes fails due to an issue with the assert function in the file src/map.c. The same issue also happens in interpreter-only mode.

* error message 
```
rv32emu: src/map.c:242: void rb_remove(map_t, map_node_t *): Assertion `nodep && nodep->node == node' failed.
Aborted (core dumped)
```

**Comment by jserv** [comment]
> ```
> rv32emu: src/map.c:242: void rb_remove(map_t, map_node_t *): Assertion `nodep && nodep->node == node' failed.
> Aborted (core dumped)
> ```

Can you use [rr](https://rr-project.org/) to debug the recording?

**Comment by jserv** [comment]
@ypaskell, can you help check rbtree related issue?

**Comment by TheCloudlet** [comment]
@qwe661234 can you provide the reproduction steps?

**Comment by qwe661234** [comment]
> @qwe661234 can you provide the reproduction steps?

The repoduction way is 
```
./build/rv32emu ./build/jit-bf.elf 
```

**Comment by jserv** [comment]
> The repoduction way is
> ```shell
> build/rv32emu build/jit-bf.elf 
> ```

This issue is more easily reproducible on x86-64 machines. However, when using the Aarch64 architecture, I haven't encountered this issue on both macOS and GNU/Linux. I am unsure if there is a hidden alignment issue or not.

**Comment by TheCloudlet** [comment]
I executed 30 times in Aarch64, and all executed properly.
I cannot reproduce the assertion since I have no x64 machines.

```
rv32emu: src/map.c:242: void rb_remove(map_t, map_node_t *): Assertion `nodep && nodep->node == node' failed.
Aborted (core dumped)
```

The assertion failure above means that we cannot find the to-be-removed target node in the map.
If I have the environment, I would set breakpoint in front of the to-be-removed target and use `find()` to confirm this.

**Comment by jserv** [comment]
> I executed 30 times in Aarch64, and all executed properly. I cannot reproduce the assertion since I have no x64 machines.

Alternatively, check the tutorial [Running x86_64-based containers on Mac computers with an Apple silicon processor](https://developer.ibm.com/tutorials/running-x86-64-containers-mac-silicon-m1/).

**Comment by visitorckw** [comment]
I quickly reviewed the relevant code and thanks to @ypaskell 's mention, "The assertion failure above means that we cannot find the to-be-removed target node in the map". It led me to think that perhaps the issue in the rb_remove function, when searching for the node to delete, might be due to using ```node->data``` for comparison instead of ```node->key```.

I conducted some simple tests on x86_64 Linux, and it appears that this correction can potentially resolve the problem. However, I haven't thoroughly reviewed other code related to the map. If I haven't misunderstood, I can make code adjustments later after my class and then send a pull request to correct this error.

**Comment by TheCloudlet** [comment]
Hi @visitorckw,

Thank you for your careful inspection.
I believe this is the root cause.
Can you test it out and submit a PR?

It's better to also modify the unit test to ensure this behavior is tested.

**Comment by visitorckw** [comment]
Thanks for your prompt response.
I'll conduct more testing, adjust the unit tests, and submit the PR later.
