### ISSUE TITLE
Assertion failed: (total_read == rv_get_reg(rv, rv_reg_a2)), function syscall_read

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#214]
After commit 56766c0653526c546f00784bbc0cefb800a6f9a2, Doom fails to launch:
```
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
Assertion failed: (total_read == rv_get_reg(rv, rv_reg_a2)), function syscall_read, file syscall.c, line 290.
/bin/sh: line 1: 12197 Abort trap: 6           ../build/rv32emu doom.elf
make: *** [doom] Error 134
```

Tested on both Ubuntu Linux 20.04 (Intel Xeon E5-2650) and macOS 14.1 (Apple M1).

**Comment by visitorckw** [comment]
I didn't encounter the assertion failure described in the issue during my tests. However, I did encounter the same error when running 'readelf,' as well as when launching 'Quake' and selecting single-player mode to enter the game, I observed the same assertion error.

**Comment by visitorckw** [comment]
Upon investigation, I discovered that this issue arises due to the incorrect assumption that the number of bytes read will always be equal to the number of bytes requested. This can occur, for example, because there are fewer bytes available at that moment (perhaps due to being close to the end-of-file) or because an error occurred during the read operation. Therefore, it is necessary to handle these scenarios.
