### ISSUE TITLE
Run emulator as gdbserver

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#22]
[rISA](https://github.com/devbored/rISA) implements an interesting GDB mode, which runs the simulator as a [gdbserver](https://sourceware.org/gdb/onlinedocs/gdb/Server.html). That is, it allows us to connect RISC-V program with a remote GDB via `target remote` or `target extended-remote` -- but without linking in the usual debugging stub. Hopefully, `rv32emu` can follow the experimental feature in rISA to provide builtin gdbserver.

See also:
* [riscv-gdbserver](https://github.com/embecosm/riscv-gdbserver): GDB Server for interacting with RISC-V models, boards and FPGAs

**Comment by jserv** [comment]
WIP: [mini-gdbstub](https://github.com/RinHizakura/mini-gdbstub)

**Comment by RinHizakura** [comment]
An experimental solution to this issue is created on [my local branch](https://github.com/RinHizakura/rv32emu/tree/gdbstub) now, which lets rv32emu support a small set of [GDB Remote Serial Protocol](https://sourceware.org/gdb/onlinedocs/gdb/Remote-Protocol.html#Remote-Protocol) packet with my [mini-gdbstub](https://github.com/RinHizakura/mini-gdbstub) library.

Here's a small example to play with the debug mode, which shows the convenience to set a breakpoint to stop the emulator by a function symbol.

rv32emu:
```
$ riscv32-unknown-elf-gcc -g tests/puzzle.c
$ ./build/rv32emu --debug a.out
```

GDB:
```
$ riscv32-unknown-elf-gdb
(gdb) file ./a.out 
Reading symbols from ./a.out...
(gdb) target remote :1234
Remote debugging using :1234
0x000100c2 in _start ()
(gdb) set debug remote 1
...
(gdb) break main
...
(gdb) cont
Continuing.
...
argc=0, argv=0xfffff004) at tests/puzzle.c:213
213	    run_puzzle();
```

A small concern here is that mini-gdbstub is still a WIP and unstable library, so it's not very convenient to use it as a submodule since we may have to sync the library frequently. I'm still thinking if that's a good idea to develop the part of gdbserver as another project. But I think mini-gdbstub is about to be integrated to rv32emu soon.

NOTE: There are still many features and possible bugs that must be refined in [mini-gdbstub](https://github.com/RinHizakura/mini-gdbstub), and rv32emu also have to provide a better implementation of the gdbstub abstraction (For example,  `rv_set_bp` should be able to set more than one breakpoint).

**Comment by jserv** [comment]
> I'm still thinking if that's a good idea to develop the part of gdbserver as another project. But I think mini-gdbstub is about to be integrated to rv32emu soon.

Both git submodule and in-repository maintenance are fine to me. Pick one when you are ready to submit pull request(s).

**Comment by jserv** [comment]
See also
* [librspd](https://github.com/nsauzede/librspd)
* [orcasim-gdbrsp](https://github.com/andersondomingues/orca-sim/tree/master/orcasim-gdbrsp)
