### ISSUE TITLE
Provide minimal cross-platform GUI library

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#332]
[Fenster](https://github.com/zserge/fenster) offers an extremely minimalistic and specific approach to displaying a cross-platform 2D canvas, characterized by its ease of use — simply include its header and begin making API calls. Integrating Fenster with rv32emu's SDL-based system calls could significantly enhance usability and simplify any future porting efforts, making it an ideal choice for streamlined, cross-platform graphical implementation.

**Comment by alanjian85** [comment]
I added the support of SDL-oriented system calls to fenster (See [fenster-rv32emu](https://github.com/alanjian85/fenster-rv32emu/tree/main)) and also issued pull requests on every repositories related to the changes I made in rv32emu. Note that the port of `fenster_audio.h` is still under development, and some functions in `fenster.h` such as `fenster_sleep()` are not optimal because rv32emu lack of a sleep system call and it doesn't seem there is a way to estimate running time under emulation precisely.

**Comment by alanjian85** [comment]
I added the support of SDL-oriented system calls to fenster (See [fenster-rv32emu](https://github.com/alanjian85/fenster-rv32emu)) and also issued pull requests on every repositories related to the changes I made in rv32emu. Note that the port of fenster_audio.h is still under development, and some functions in `fenster.h` such as `fenster_sleep()` are not optimal because rv32emu lack of a sleep system call and it doesn't seem there is a way to estimate running time under emulation precisely.

**Comment by alanjian85** [comment]
The ported fenster library is still under my personal account. To provide a convenient access point for others to use, it is better to fork and maintain it under this organization. Besides, the code in [fenster-rv32emu](https://github.com/alanjian85/fenster-rv32emu) should be reviewed before forking it.
