### ISSUE TITLE
Incorrect emulation for micro-AES

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#99]
[µAES](https://github.com/polfosol/micro-AES) is a minimalist ANSI-C compatible code for the AES encryption and block cipher modes. In this repository, the prebuilt binary `build/aes.elf` is provided for testing purpose. However, rv32emu would behave differently than expected when compared to [Spike](https://github.com/riscv-software-src/riscv-isa-sim) and [rv8](https://github.com/michaeljclark/rv8).

[ Spike ]
```shell
riscv-isa-sim/build/spike --isa=RV32G riscv-pk/build/pk aes.elf 
```

Results:
```
AES-128 EAX encryption: PASSED!
AES-128 EAX decryption: PASSED!
```

[ rv8 ]
```shell
rv-jit aes.elf
```

Results:
```
AES-128 EAX encryption: PASSED!
AES-128 EAX decryption: PASSED!
```

[ rv32emu ]
```shell
rv32emu aes.elf
```

Results:
```
AES-128 EAX encryption: FAILED :(
AES-128 EAX decryption: FAILED :(
```

**Comment by qwe661234** [comment]
After investigating the functions `AES_EAX_encrypt` and `AES_EAX_decrypt`, I discovered that the problem in `rv32emu` is caused by this type of casting statement.
```c
// type of crtxt and mac is uint8_t
*(int32_t *) &crtxt[ptextLen] = *(int32_t *) &mac[12];
```
This type of casting statement appears only in the functions `AES_EAX_encrypt` and `AES_EAX_decrypt`; if the statement is changed to this
```c
// type of crtxt and mac is uint8_t
for(int i = 0; i < 4; i++) {
    crtxt[ptextLen + i] = mac[12 + i];
}
```
, the test will pass. So, I'll use what I've discovered to solve the problem.

**Comment by jserv** [comment]
> the test will pass. So, I'll use what I've discovered to solve the problem.

Compatibility is a crucial issue from the ISA emulator's point of view. We would make sure that rv32emu behaves exactly like the reference RISC-V ISA simulator, Spike.

**Comment by qwe661234** [comment]
This problem is similar to issue #82, in that the `ptextLen` is 57, and this statement 
```c
*(int32_t *) &crtxt[ptextLen] = *(int32_t *) &mac[12];
```
wishes to load a word from the start address of `crtxt` + 57. However, because this address is not aligned by 4, the exception handler is invoked, and the result is unexpected. This test will pass if we close the address alignment checking in `clw` and `csw` instruction emulation. However, I am not convinced that closing address alignment checking is a good idea.

**Comment by qwe661234** [comment]
Perhaps we should allow the load and store instructions to access data whose address is not aligned by 4. Because this exception may occur frequently when attempting to access a word in a byte array.

**Comment by jserv** [comment]
> Perhaps we should allow the load and store instructions to access data whose address is not aligned by 4. Because this exception may occur frequently when attempting to access a word in a byte array.

Check [-m[no-]strict-align](https://github.com/riscv-collab/riscv-gcc/issues/58) in GCC and its rationale. In RV32I, support for misaligned	memory access is mandatory.

**Comment by qwe661234** [comment]
I add flag `-mno-strict-align` or `-mstrict-align` to compile `aes.c`, but our emulator still fails the test. When an exception handler is called in our emulator, the `load` or `store` instructions become invalid, and nothing in memory changes. That's the reason why test fails.

**Comment by qwe661234** [comment]
> In RV32I, support for misaligned memory access is mandatory.

Perhaps we should modify our exception handler. For example, if we still want to load a word from address 0x3, we can combine the last byte of the word stored in address 0x0 and the first three bytes of the word stored in address 0x4. Instead of simply returning false, include this operation in the exception handler.

**Comment by qwe661234** [comment]
In `Spike`, function `store_slow_path` deals with unaligned memory access, function `store_slow_path` would check if unaligned memory access is enabled (setting in config). If unaligned memory access is enabled, store instruction would utilize `memcpy` to store value, instead of assigning value directly.

**Comment by jserv** [comment]
> In `Spike`, function `store_slow_path` deals with unaligned memory access, function `store_slow_path` would check if unaligned memory access is enabled (setting in config). If unaligned memory access is enabled, store instruction would utilize `memcpy` to store value, instead of assigning value directly.

Here, the slow path for memory read/write operations should be revised together with execution iterations in conjunction with tail-call optimization. What would you suppose to make further changes?

**Comment by qwe661234** [comment]
> > In `Spike`, function `store_slow_path` deals with unaligned memory access, function `store_slow_path` would check if unaligned memory access is enabled (setting in config). If unaligned memory access is enabled, store instruction would utilize `memcpy` to store value, instead of assigning value directly.
> 
> Here, the slow path for memory read/write operations should be revised together with execution iterations in conjunction with tail-call optimization. What would you suppose to make further changes?

After comparing `Spike` and `rv32emu` implementations, I think we do not need to change the implementation. The reason for this is that instead of reading or writing a word or a half-word like `Spike`, our memory operation reads or writes memory bytes by bytes. To elaborate, in `Spike`, the `lw` instruction assigns a word to distination, but in `rv32emu`, it assigns a byte four times to distination. So, what we need to change is to check whether unaligned memory access is enabled before allowing the user to access an unaligned memory address.
* lw, lh ...
```c
if ((addr & 3) && !misaligned_enabled){
    // call exception handler
}
// load value
```
* sw, sh, sb... 
```c
if ((addr & 3) && !misaligned_enabled){
    // call exception handler
}
// store value
```

**Comment by jserv** [comment]
> The reason for this is that instead of reading or writing a word or a half-word like `Spike`, our memory operation reads or writes memory bytes by bytes. To elaborate, in `Spike`, the `lw` instruction assigns a word to distination, but in `rv32emu`, it assigns a byte four times to distination. So, what we need to change is to check whether unaligned memory access is enabled before allowing the user to access an unaligned memory address.

As opposed to Spike, rv32emu's byte-oriented memory operations may lead to performance loss. Let's track in another issue.

**Comment by qwe661234** [comment]
In issue #122, we have implemented significant improvements to the memory read/write functionality. Furthermore, we have resolved the issue of disabled unaligned memory access. As a result, our new implementation allows us to access memory even when the memory address is unaligned.

**Comment by jserv** [comment]
Duplicated in #122
